#pragma once
static const char PAGE[] PROGMEM=R"HTML(<!doctype html><html lang="zh-CN"><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>共感娃娃设置</title>
<style>body{font:16px system-ui;background:#f3f1e9;color:#263e33;max-width:820px;margin:24px auto;padding:16px}section{background:white;padding:22px;border-radius:16px;margin:16px 0}input,select,button{font:inherit;box-sizing:border-box;padding:10px;margin:6px 0;border:1px solid #bdcbc0;border-radius:8px;width:100%}input[type=checkbox]{width:auto}button{background:#2b6249;color:white;cursor:pointer}button:disabled{opacity:.5}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:10px}small{color:#63736a}pre,code{white-space:pre-wrap;overflow-wrap:anywhere}#error{color:#a1372a}li{margin:10px 0}a{color:#2b6249}</style>
<h1>共感娃娃 · 设置</h1><p id="state">读取设备状态…</p><p id="error" role="alert"></p>
<section><h2>Wi-Fi 配网</h2><p id="setupNote"></p><button id="scan">扫描附近 Wi-Fi</button><select id="networks"><option value="">请选择网络</option></select><small id="scanHint">只支持 2.4 GHz；隐藏网络可手动填写。</small><input id="ssid" maxlength="32" placeholder="Wi-Fi 名称"><input id="password" type="password" maxlength="63" placeholder="Wi-Fi 密码（开放网络留空）"><button id="join">保存并连接</button><p id="joinResult"></p><small>有配置时慢闪尝试联网，60 秒失败后开配网热点并快闪；联网常亮并关闭热点。运行中长按 BOOT 约 3 秒重新配网。</small></section>
<section><h2>通道类型与部位</h2><p>最多 16 个逻辑通道，现有 4051 提供 8 个模拟输入。选择压力、NTC 温度输入或震动输出；新通道默认仅模拟。修改类型和接口后请保存。</p><div id="parts" class="grid"></div><button id="addChannel">添加通道</button><button id="saveParts">保存全部通道配置</button><p id="partResult"></p><small>温度默认 NTC10k/B3950；4051 分支按现有 4.7k 串联、10k 下拉计算，可展开修改参数。震动必须使用独立 GPIO 和板外驱动，不能接 FSR 接口。</small></section>
<section><h2>输入与模拟测试</h2><p id="sensorMode"></p><select id="channel"></select><label id="inputUnit">压力原始值</label><input id="pressure" type="number" value="3200" aria-label="模拟输入值"><button id="press">发送模拟输入（压力 5 秒释放）</button><button id="release">释放当前压力通道</button><details><summary>真实输入采样</summary><p>仅在传感器电路接好后启用；重启默认关闭。每路压力阈值和温度参数在通道卡片内配置。</p><label><input id="physical" type="checkbox">已接好传感器，启用真实输入</label><button id="sensors">应用输入开关</button><pre id="raw"></pre></details><pre id="values"></pre><pre id="result"></pre></section>
<section><h2>震动输出测试</h2><select id="vibrationChannel" aria-label="震动通道"></select><label>强度（%）<input id="intensity" type="number" min="0" max="100" value="40"></label><label>持续时间（ms，最长 5000）<input id="duration" type="number" min="1" max="5000" value="500"></label><button id="vibrate">发送震动命令</button><button id="stopVibration">立即停止</button><label><input id="outputEnabled" type="checkbox">已确认接好板外电机驱动，允许真实 PWM 输出</label><button id="saveOutput">应用输出开关</button><small>仅模拟接口会记录命令，不驱动硬件。真实输出上电、重启和保存通道配置后均关闭；超时自动停止。日志表示命令，不表示实际电机反馈。</small></section>
<section><h2>MCP 设置</h2><label><input id="enabled" type="checkbox">允许设备局域网 MCP</label><button id="saveMcp">保存 MCP 开关</button><p>设备端点：<code id="endpoint"></code></p><details><summary>查看 MCP 令牌与设备管理密码</summary><p>Bearer Token：<code id="token"></code></p><p>联网后设置页账号：admin；密码：<code id="adminPassword"></code></p></details><small>这里是设备短期事件接口。长期历史、人设与互动会话请安装电脑端 Companion MCP。</small></section>
<section><h2>设备触摸日志</h2><small>实时显示开始／结束、部位及原始压力。此页最多显示最近 40 条；长期历史由电脑采集服务保存。</small><button id="refreshLogs">刷新日志</button><p id="logNote"></p><ol id="logs"></ol></section>
<style>.channel-card{border:1px solid #dce3db;padding:12px;border-radius:10px}.channel-card textarea{width:100%;box-sizing:border-box}.channel-card input[type=checkbox]{width:auto}</style>
<script src="/channel-editor.js"></script><script>
let cfg={},cursor=0,boot='',polling=false;const $=id=>document.getElementById(id);
async function api(path,data){const r=await fetch(path,{method:data?'POST':'GET',headers:{'Content-Type':'application/json','X-Setup-Token':cfg.token||''},body:data?JSON.stringify(data):undefined});const raw=await r.text();let d;try{d=JSON.parse(raw)}catch(e){throw Error('设备暂时不可用；配网成功后请切回家庭网络，再打开设备新地址。')}if(!r.ok||d.error)throw Error(typeof d.error==='string'?d.error:JSON.stringify(d.error||d));return d}
async function tool(name,args={}){const r=await api('/api/tool',{jsonrpc:'2.0',id:1,method:'tools/call',params:{name,arguments:args}});return JSON.parse(r.result.content[0].text)}
function bind(id,fn){$(id).onclick=async()=>{$(id).disabled=true;try{$('error').textContent='';await fn()}catch(e){$('error').textContent=e.message}finally{$(id).disabled=false}}}
async function status(){const s=await api('/api/status');$('state').textContent=s.wifi_connected?'已联网：'+s.ssid+' · '+s.ip:'网络状态：'+s.network_mode;$('setupNote').textContent=s.config_ap_open?'正在提供无密码热点 '+s.ap_ssid+'，手动配网地址 http://192.168.4.1/ 。连接成功后热点会关闭。':'配置热点已关闭；可在这里修改网络。';$('endpoint').textContent='http://'+(s.wifi_connected?s.ip:s.ap_ip)+'/mcp';const sc=await tool('get_sensor_config');$('sensorMode').textContent=sc.enabled?'真实输入采样已启用':'真实输入已关闭，可进行模拟测试';$('raw').textContent='已配置通道原始值：'+sc.raw.join(', ');await updateChannelReadings()}
async function parts(){await loadChannels()}
async function logs(){const d=await tool('get_touch_events',{after:cursor,boot_id:boot});if(d.boot_changed){$('logs').replaceChildren();cursor=0}boot=d.boot_id;cursor=d.next_cursor;$('logNote').textContent=d.gap?'队列有缺口，部分旧记录已被覆盖。':'';for(const e of d.events){const li=document.createElement('li');li.textContent=e.source+' · '+e.body_part+' / CH'+e.channel+' · '+e.sensor_type+' / '+e.direction+' · '+e.phase+' · '+(e.value==null?'无有效值':e.value+' '+e.unit)+' · '+e.quality;$('logs').prepend(li)}while($('logs').children.length>40)$('logs').lastChild.remove()}
$('networks').onchange=()=>{$('ssid').value=$('networks').value};
bind('scan',async()=>{$('scanHint').textContent='正在扫描…';let d=await api('/api/scan',{start:true});for(let i=0;d.scanning&&i<35;i++){await new Promise(r=>setTimeout(r,800));d=await api('/api/scan',{start:false})}if(d.scanning)throw Error('扫描超时，请重试');$('networks').replaceChildren(new Option('请选择网络',''));for(const n of d.networks)$('networks').add(new Option(n.ssid+' · '+n.rssi+' dBm'+(n.secure?' · 需密码':' · 开放'),n.ssid));$('scanHint').textContent='找到 '+d.networks.length+' 个网络'});
bind('join',async()=>{await api('/api/wifi',{ssid:$('ssid').value,password:$('password').value});$('password').value='';$('joinResult').textContent='正在尝试联网。成功后热点关闭，请切回家庭网络；失败时保留配网热点。'});
bind('saveParts',async()=>{await saveChannelEditor();$('physical').checked=false;$('outputEnabled').checked=false;await status()});
bind('press',async()=>{$('result').textContent=JSON.stringify(await simulateSelected(),null,2);await logs()});
bind('release',async()=>{await tool('doll_simulate_press',{channel:Number($('channel').value),value:0});await logs()});
bind('sensors',async()=>{await tool('set_input_enabled',{enabled:$('physical').checked});await status()});
bind('saveOutput',async()=>{await tool('set_output_enabled',{enabled:$('outputEnabled').checked,external_driver_confirmed:$('outputEnabled').checked});await status()});
bind('vibrate',async()=>{$('result').textContent=JSON.stringify(await runVibration(),null,2);await logs()});bind('stopVibration',async()=>{await runVibration(0);await logs()});$('channel').onchange=inputTypeChanged;
bind('saveMcp',async()=>{await api('/api/mcp',{enabled:$('enabled').checked});$('result').textContent='设备 MCP 开关已保存'});bind('refreshLogs',logs);
(async()=>{try{cfg=await api('/api/setup');$('token').textContent=cfg.token;$('adminPassword').textContent=cfg.admin_password;$('enabled').checked=cfg.enabled;const sc=await tool('get_sensor_config');$('physical').checked=sc.enabled;await parts();const v=await updateChannelReadings();$('outputEnabled').checked=v.physical_outputs_enabled;await status();await logs()}catch(e){$('error').textContent=e.message}setInterval(async()=>{if(polling)return;polling=true;try{await status();await logs()}catch(e){$('state').textContent='连接已中断。如刚配网成功，请切回家庭网络访问设备。'}finally{polling=false}},2500)})();
</script></html>)HTML";
