const fs=require('fs'),path=require('path'),{spawn}=require('child_process'),{chromium}=require('playwright');
(async()=>{
 const root=path.resolve(__dirname,'..'),python=process.argv[2];if(!python)throw Error('Pass Python executable as argument');
 const fixture=spawn(python,[path.join(__dirname,'test_history_ui_fixture.py')],{cwd:root,windowsHide:true,stdio:['ignore','pipe','pipe']});
 let browser;
 try{
  const base=await new Promise((resolve,reject)=>{let output='',diagnostic='';const timer=setTimeout(()=>reject(Error('Fixture startup timed out: '+diagnostic.slice(-1000))),15000);
   fixture.stdout.on('data',chunk=>{output+=chunk;const url=output.match(/http:\/\/127\.0\.0\.1:\d+/);if(url){clearTimeout(timer);resolve(url[0]);}});
   fixture.stderr.on('data',chunk=>{diagnostic+=chunk;diagnostic=diagnostic.slice(-2000);});
   fixture.once('exit',code=>{clearTimeout(timer);reject(Error('Fixture exited '+code+': '+diagnostic));});fixture.once('error',reject);
  });
  const executable=[chromium.executablePath(),'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe','C:/Program Files/Google/Chrome/Application/chrome.exe'].find(fs.existsSync);
  browser=await chromium.launch({headless:true,executablePath:executable});const page=await browser.newPage({viewport:{width:390,height:900},acceptDownloads:true}),errors=[];
  page.on('pageerror',e=>errors.push(e.message));
  await page.goto(base+'/companion');await page.waitForFunction(()=>document.querySelector('#retentionStatus').textContent.includes('自动删除已关闭'));
  await page.uncheck('#live');await page.click('#queryHistoryStats');
  await page.waitForFunction(()=>document.querySelector('#historyStatistics').textContent.includes('606 条事件'));
  if(!(await page.textContent('#historyStatistics')).includes('1 次压力开始'))throw Error('Pressure summary incorrect');
  await page.selectOption('#manageTimeScope','all');await page.click('#queryHistoryStats');
  await page.waitForFunction(()=>document.querySelector('#historyStatistics').textContent.includes('607 条事件'));
  const jsonPromise=page.waitForEvent('download');await page.click('#exportHistoryJson');const jsonDownload=await jsonPromise;
  const exported=JSON.parse(fs.readFileSync(await jsonDownload.path(),'utf8'));
  if(exported.records.length!==607||new Set(exported.records.map(e=>e.id)).size!==607||!exported.records.some(e=>e.at===null))throw Error('Paginated JSON export lost/duplicated/dated records');
  const csvPromise=page.waitForEvent('download');await page.click('#exportHistoryCsv');const csv=fs.readFileSync(await(await csvPromise).path(),'utf8');
  if((csv.match(/payload_json/g)||[]).length!==1||!csv.includes("'=fixture_formula"))throw Error('CSV header/formula protection failed');
  await page.selectOption('#manageTimeScope','unknown');await page.click('#queryHistoryStats');
  await page.waitForFunction(()=>document.querySelector('#historyStatistics').textContent.includes('1 条事件'));
  if(await page.inputValue('#manageFrom')!=='')throw Error('Unknown occurrence time has a date filter');
  await page.selectOption('#manageTimeScope','all');await page.fill('#manageBody','TEST-HISTORY-PRESSURE');
  await page.locator('#historyManagement details').filter({has:page.locator('#previewHistoryDelete')}).locator('summary').click();
  await page.click('#previewHistoryDelete');await page.waitForFunction(()=>document.querySelector('#deletionPreview').textContent.includes('将删除 2 条事件'));
  if(!(await page.locator('#confirmHistoryDelete').isDisabled()))throw Error('Delete enabled before approval');
  await page.check('#deleteApproval');await page.fill('#manageBody','changed');await page.locator('#manageBody').blur();
  if(!(await page.locator('#confirmHistoryDelete').isDisabled()))throw Error('Changed filters kept old approval');
  await page.fill('#manageBody','TEST-HISTORY-PRESSURE');await page.click('#previewHistoryDelete');
  await page.waitForFunction(()=>document.querySelector('#deletionPreview').textContent.includes('将删除 2 条事件'));await page.check('#deleteApproval');await page.click('#confirmHistoryDelete');
  await page.waitForFunction(()=>document.querySelector('#historyManagementResult').textContent.includes('已删除 2 条事件'));
  await page.fill('#manageBody','');await page.click('#queryHistoryStats');await page.waitForFunction(()=>document.querySelector('#historyStatistics').textContent.includes('605 条事件'));
  await page.locator('#historyManagement details').filter({has:page.locator('#saveRetention')}).locator('summary').click();
  await page.fill('#retentionDays','90');await page.check('#retentionEnabled');
  page.once('dialog',dialog=>dialog.dismiss());await page.click('#saveRetention');
  const policy=await page.evaluate(()=>api('/companion/tool',{name:'get_history_retention',arguments:{}}));if(policy.enabled)throw Error('Cancelled retention enabled deletion');
  page.once('dialog',dialog=>dialog.accept());await page.click('#saveRetention');await page.waitForFunction(()=>document.querySelector('#retentionStatus').textContent.includes('已启用'));
  await page.uncheck('#retentionEnabled');await page.click('#saveRetention');await page.waitForFunction(()=>document.querySelector('#retentionStatus').textContent.includes('已关闭'));
  if(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth+2))throw Error('390px overflow');if(errors.length)throw Error(errors.join('\n'));
  await page.locator('#historyManagement').screenshot({path:path.join(root,'build/device-lab/history-management-fixture-mobile.png')});
  const report={passed:true,at:new Date().toISOString(),fixture_only:true,checks:['607 real fixture rows, full-scope statistics','multi-page JSON and CSV downloads','unknown time isolation','exact two-event preview and explicit approval','changed filters invalidate preview','confirmed deletion against disposable archive','retention cancel/enable/disable','390px layout and no JavaScript errors'],owner_history_deleted:false};
  fs.writeFileSync(path.join(root,'build/device-lab/history-ui-test.json'),JSON.stringify(report,null,2));console.log(JSON.stringify(report));
 }finally{if(browser)await browser.close();fixture.kill();}
})().catch(e=>{console.error(e);process.exitCode=1});
